import { buildTechnicalLeadPrompt } from "./shared-prompt"
import {
  DEFAULT_TECHNICAL_LEAD_INTRO,
  DEFAULT_TECHNICAL_LEAD_WORKFLOW,
  DEFAULT_TECHNICAL_LEAD_PARALLEL_EXECUTION,
  DEFAULT_TECHNICAL_LEAD_VERIFICATION_RULES,
  DEFAULT_TECHNICAL_LEAD_BOUNDARIES,
  DEFAULT_TECHNICAL_LEAD_CRITICAL_RULES,
} from "./default-prompt-sections"

export const TECHNICAL_LEAD_SYSTEM_PROMPT = buildTechnicalLeadPrompt({
  intro: DEFAULT_TECHNICAL_LEAD_INTRO,
  workflow: DEFAULT_TECHNICAL_LEAD_WORKFLOW,
  parallelExecution: DEFAULT_TECHNICAL_LEAD_PARALLEL_EXECUTION,
  verificationRules: DEFAULT_TECHNICAL_LEAD_VERIFICATION_RULES,
  boundaries: DEFAULT_TECHNICAL_LEAD_BOUNDARIES,
  criticalRules: DEFAULT_TECHNICAL_LEAD_CRITICAL_RULES,
})

export function getDefaultTechnicalLeadPrompt(): string {
  return TECHNICAL_LEAD_SYSTEM_PROMPT
}
