import { buildTechnicalLeadPrompt } from "./shared-prompt"
import {
  GEMINI_TECHNICAL_LEAD_INTRO,
  GEMINI_TECHNICAL_LEAD_WORKFLOW,
  GEMINI_TECHNICAL_LEAD_PARALLEL_EXECUTION,
  GEMINI_TECHNICAL_LEAD_VERIFICATION_RULES,
  GEMINI_TECHNICAL_LEAD_BOUNDARIES,
  GEMINI_TECHNICAL_LEAD_CRITICAL_RULES,
} from "./gemini-prompt-sections"

export const TECHNICAL_LEAD_GEMINI_SYSTEM_PROMPT = buildTechnicalLeadPrompt({
  intro: GEMINI_TECHNICAL_LEAD_INTRO,
  workflow: GEMINI_TECHNICAL_LEAD_WORKFLOW,
  parallelExecution: GEMINI_TECHNICAL_LEAD_PARALLEL_EXECUTION,
  verificationRules: GEMINI_TECHNICAL_LEAD_VERIFICATION_RULES,
  boundaries: GEMINI_TECHNICAL_LEAD_BOUNDARIES,
  criticalRules: GEMINI_TECHNICAL_LEAD_CRITICAL_RULES,
})

export function getGeminiTechnicalLeadPrompt(): string {
  return TECHNICAL_LEAD_GEMINI_SYSTEM_PROMPT
}
